ClubManagement/Controllers/MatchController.cs
using ClubManagement.DAL;
using ClubManagement.Models;
using ClubManagement.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClubManagement.Controllers
{
    public class MatchController : Controller
    {
        // GET: Match
        [Authorize]
        public ActionResult List()
        {
            ClubContext db = new ClubContext();

            var matches =
            from e in db.Matches
            select e;

            matches = matches.OrderByDescending(s => s.Day);
            

            return View(matches.ToList());
        }
        public ActionResult Delete(int id)
        {
            ClubContext db = new ClubContext();
            Match match = new Match();
            db.Matches.Attach(match);
            match = db.Matches.Find(id);
            db.Matches.Remove(match);
            db.SaveChanges();
            return RedirectToAction("List");
        }
        public ActionResult AddPlayers(int id)
        {
            ClubContext db = new ClubContext();
            Match match = new Match();
            db.Matches.Attach(match);
            match = db.Matches.Find(id);
            ViewBag.Name = match.Opponent;
            ViewBag.Day = match.Day.Date;
            List<Player> playersList = db.Players.ToList();
            List<string> playersListString = new List<string>();

            Match m = new Match()
            {

                Players = playersList,

            };

            return View(m);
        }
        [HttpPost]
        public ActionResult AddPlayers(Training training, int id, FormCollection colletion)
        {
            var b = colletion["Players"].ToString();
           
            b.ToArray();
            ClubContext db = new ClubContext();
            Match match = new Match();
            List<Player> matchPlayers = new List<Player>();
            string[] splitted = b.Split(',');
            int[] ids = new int[splitted.Length];

            for (int i = 0; i < splitted.Length; i++)
            {
                ids[i] = int.Parse(splitted[i]);
            }
            for (int i=0; i<ids.Count(); i++)
            {
                matchPlayers.Add(db.Players.Find(ids[i]));
            }
            
            string lista = "";
            string name = "";
            Player player = new Player();
            foreach (var item in matchPlayers)
            {
                db.Players.Attach(item);
                player = db.Players.Find(Convert.ToInt32(item.id));
                player.Games++;
                db.Entry(player).State = EntityState.Modified;
                db.SaveChanges();
                name = player.Name + " " + player.Surname;
                lista = lista + name + ", ";
            }

            Match match1 = new Match();
            db.Matches.Attach(match1);
            match1 = db.Matches.Find(id);
            match1.IdPlayers =  string.Join(",",ids); 
            match1.Updated = true;
            match1.PlayersString = lista;
            db.Entry(match1).State = EntityState.Modified;
            db.SaveChanges();


            return RedirectToAction("List");
        }
        public ActionResult Details(int id)
        {
            ClubContext db = new ClubContext();

            Match m = new Match();
            db.Matches.Attach(m);
            m = db.Matches.Find(id);

            return View(m);
        }
        public ActionResult AddStats(int id)
        {
            ClubContext db = new ClubContext();
            Match m = new Match();
            db.Matches.Attach(m);
            m = db.Matches.Find(id);
            if (!m.Updated)
            {
                Response.Write("<script>alert('Data inserted successfully')</script>");
                return RedirectToAction("List");
            }
            else
            {
                List<Player> players = new List<Player>();
                List<PlayerToMatch> playersVM = new List<PlayerToMatch>();
                PlayerToMatch pVM;
                List<PlayerToMatch> checkMatch = db.PlayerToMatches.ToList();
                string[] splitted = m.IdPlayers.Split(',');
                int[] ids = new int[splitted.Length];

                for (int i = 0; i < splitted.Length; i++)
                {
                    ids[i] = int.Parse(splitted[i]);
                }

                for (int i = 0; i < ids.Count(); i++)
                {
                    players.Add(db.Players.Find(ids[i]));

                }
                ViewBag.MatchDay = m.Time;
                ViewBag.Opponent = m.Opponent;
                ViewBag.Score = m.GoalsLost.ToString() + ":" + m.GoalsScored.ToString();
                if (!m.AddedPLayersToMatch)
                {

                    foreach (Player item in players)
                    {

                        pVM = new PlayerToMatch
                        {
                            PlayerId = item.id,
                            MatchId = m.Id,
                            Name = item.Name,
                            Surname = item.Surname,
                            YellowCards = 0,
                            RedCards = 0,
                            Goals = 0,
                            Minutes = 0,
                            Rating = 0,
                            Assists = 0,

                        };
                        playersVM.Add(pVM);
                        db.PlayerToMatches.Add(pVM);
                        db.SaveChanges();

                    }

                }

                m.AddedPLayersToMatch = true;
                db.SaveChanges();
                List<PlayerToMatch> playersToView = db.PlayerToMatches.Where(item => item.MatchId == id).OrderByDescending(item => item.Minutes).ToList();
                return View(playersToView);
            }
        }

        public ActionResult Edit(int id)
        {
            ClubContext db = new ClubContext();
            PlayerToMatch p = db.PlayerToMatches.Find(id);
            Match m = db.Matches.Find(p.MatchId);

            ViewBag.Opponent = m.Opponent;
            return View(p);
        }
        [HttpPost]
        public ActionResult Edit(PlayerToMatch p,int id)
        {

            ClubContext db = new ClubContext();
            PlayerToMatch player = new PlayerToMatch();
            Player playerToAdd = new Player();
            
            db.PlayerToMatches.Attach(player);
            player = db.PlayerToMatches.Find(id);
            playerToAdd = db.Players.Find(player.PlayerId);
            playerToAdd.YellowCards = playerToAdd.YellowCards + p.YellowCards;
            playerToAdd.RedCards = playerToAdd.RedCards + p.RedCards;
            playerToAdd.Minutes = playerToAdd.Minutes + p.Minutes;
            playerToAdd.Assists = playerToAdd.Assists + p.Assists;
            playerToAdd.RatingSum = playerToAdd.RatingSum + p.Rating;
            db.PlayerToMatches.Attach(player);
            player = db.PlayerToMatches.Find(id);

            player.YellowCards = p.YellowCards;
            player.RedCards = p.RedCards;
            player.Minutes = p.Minutes;
            player.Goals = p.Goals;
            player.Assists = p.Assists;
            player.Rating = p.Rating;

            db.Entry(playerToAdd).State = EntityState.Modified;
            db.Entry(player).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("AddStats", new { id = player.MatchId });
        }

        public ActionResult EditMatch (int id)
        {
            ClubContext db = new ClubContext();
            Match m = db.Matches.Find(id);
            return View(m);
        }
        [HttpPost]
        public ActionResult EditMatch (Match m, int id)
        {
            ClubContext db = new ClubContext();
            Match match = db.Matches.Find(id);
            match.GoalsLost = m.GoalsLost;
            match.GoalsScored = m.GoalsScored;
            Opponent oponnent = db.Opponents.Find(match.OpponentID);
            if (m.GoalsScored > m.GoalsLost) oponnent.Wins++;
            else if (m.GoalsScored < m.GoalsLost) oponnent.Loses++;
            else oponnent.Draws++;
            oponnent.LostGoals = oponnent.LostGoals + m.GoalsLost;
            oponnent.ScoredGoals = oponnent.ScoredGoals + m.GoalsScored;
            db.Entry(match).State = EntityState.Modified;
            db.Entry(oponnent).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("List");
        }
        public ActionResult PlayedMatches ( int id)
        {
            ClubContext db = new ClubContext();
            List<PlayerToMatch> matches = db.PlayerToMatches.Where(s => s.PlayerId == id).ToList();
            return View(matches);

        }
      
    }
}

ClubManagement/Controllers/PlayerController.cs
using ClubManagement.DAL;
using ClubManagement.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClubManagement.Controllers
{
    public class PlayerController : Controller
    {
        // GET: Player
        [Authorize]
        public ActionResult List(int? sortOrder)
        {
           
            ClubContext mDb = new ClubContext();
            var playersList = 
            from p in mDb.Players
            select p;
            
            
            //sss
            //playersList.Sort((p, q) => p.Position.CompareTo(q.Position));
            switch (sortOrder)
            {
                case 1:
                    playersList= playersList.OrderBy(s => s.Brithday);
                    break;
                case 2:
                    playersList = playersList =playersList.OrderBy(s => s.Position);
                    break;
                case 3:
                    playersList = playersList.OrderBy(s => s.Examination);
                    break;
                case 4:
                    playersList = playersList.OrderByDescending(s => s.Goals);
                    break;
                case 5:
                    playersList = playersList.OrderByDescending(s => s.Assists);
                    break;
                case 6:
                    playersList = playersList.OrderByDescending(s => s.Games);
                    break;
                case 7:
                    playersList = playersList.OrderByDescending(s => s.Minutes);
                    break;
                case 8:
                    playersList = playersList.OrderByDescending(s => s.YellowCards);
                    break;
                case 9:
                    playersList = playersList.OrderByDescending(s => s.RedCards);
                    break;
                case 10:
                    playersList = playersList.OrderByDescending(s => s.Absence);
                    break;
                case 11:
                    playersList = playersList.OrderBy(s => s.Surname);
                    break;
                default:
                    playersList=playersList.OrderBy(s => s.Surname);
                    break;
            }
            return View(playersList.ToList());
            
        }
        public ActionResult Create()
        {
          //  var u = Session["rola"] as string;
         //   if (u != "admin") return RedirectToAction("MainPage", "Home");
         //      else
            return View();
        }
        [HttpPost]
        public ActionResult Create(Player player,HttpPostedFileBase file)

        {

            string path;
            if (!ModelState.IsValid) return View("Create", player);
            
                else
            {
                
                Player p = new Player
                {
                    id= player.id,
                    Name = player.Name,
                    Surname = player.Surname,
                    Nationality = player.Nationality,
                    YellowCards = 0,
                    RedCards = 0,
                    Minutes = 0,
                    Goals = 0,
                    Assists = 0,
                    AvgRating=0,
                    Games=0,
                    RatingSum=0,
                    Brithday = player.Brithday,
                    Position = player.Position,
                    Absence = player.Absence,
                    Examination= player.Examination,


                };
                if(file==null) path = Path.Combine(Server.MapPath("~/Content/Images"), Path.GetFileName("bezzdjęcia.png"));
                else path = Path.Combine(Server.MapPath("~/Content/Images"), Path.GetFileName(file.FileName));
                file.SaveAs(path);
                p.ImgSource = file.FileName;
                ClubContext db = new ClubContext();
                db.Players.Add(p);
                db.SaveChanges();

                return RedirectToAction("List");
            }
        }
        public ActionResult Details(int id)
        {
            ClubContext db = new ClubContext();
            Player player = new Player();
            db.Players.Attach(player);
            player = db.Players.Find(id);
            Player p = new Player
            {
                id = player.id,
                Name = player.Name,
                Surname = player.Surname,
                Nationality = player.Nationality,
                YellowCards = player.YellowCards,
                RedCards = player.RedCards,
                Minutes = player.Minutes,
                Goals = player.Goals,
                Assists = player.Assists,
                Games = player.Games,
                Brithday = player.Brithday,
                Position = player.Position,
                Absence = player.Absence,
                Examination = player.Examination,
                ImgSource=player.ImgSource,
                AvgRating = Math.Round((double)player.RatingSum / (double)player.Games,2),

            };

            return View(p);
        }
        public ActionResult Edit(int id)
        {
            ClubContext db = new ClubContext();
            Player player = new Player();
            db.Players.Attach(player);
            player = db.Players.Find(id);
            Player p = new Player()
            {
                id = player.id,
                Name = player.Name,
                Surname = player.Surname,
                Nationality = player.Nationality,
                YellowCards = player.YellowCards,
                RedCards = player.RedCards,
                Minutes = player.Minutes,
                Goals = player.Goals,
                Assists = player.Assists,
                Games = player.Games,
                Brithday = player.Brithday,
                Position = player.Position,
                Absence = player.Absence,
                Examination = player.Examination,


            };

            return View(p);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[Authorize]
        public ActionResult Edit(Player p, int id)
        {
            
            
                ClubContext db = new ClubContext();
                Player player = new Player();
                db.Players.Attach(player);
                player = db.Players.Find(id);
               
                player.YellowCards = p.YellowCards;
                player.RedCards = p.RedCards;
                player.Minutes = p.Minutes;
                player.Goals = p.Goals;
                player.Assists = p.Assists;
                player.Games = p.Games;
                player.Absence = p.Absence;
                db.Entry(player).State = EntityState.Modified;
                db.SaveChanges();
            
          //  else return View("Edit", p);
            return RedirectToAction("List");


        }
        public ActionResult Delete(int id)
        {
            ClubContext db = new ClubContext();
            Player player = new Player();
            db.Players.Attach(player);
            player = db.Players.Find(id);
            db.Players.Remove(player);
            db.SaveChanges();
            return RedirectToAction("List");
        }
        public ActionResult EditInfo(int id)
        {
            ClubContext db = new ClubContext();
            Player player = new Player();
            db.Players.Attach(player);
            player = db.Players.Find(id);
            Player p = new Player()
            {
                id = player.id,
                Name = player.Name,
                Surname = player.Surname,
                Nationality = player.Nationality,               
                Brithday = player.Brithday,
                Examination = player.Examination,


            };

            return View(p);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[Authorize]
        public ActionResult EditInfo(Player p, int id)
        {


            ClubContext db = new ClubContext();
            Player player = new Player();
            db.Players.Attach(player);
            player = db.Players.Find(id);

            player.Examination = p.Examination;
            player.Position = p.Position;
            
            db.Entry(player).State = EntityState.Modified;
            db.SaveChanges();

            //  else return View("Edit", p);
            return RedirectToAction("List");


        }
    }
}

ClubManagement/Views/Player/Create.cshtml
@model ClubManagement.Models.Player

@{
    ViewBag.Title = "Create";
}

<h2>Dodaj nowego zawodnika</h2>


@using (Html.BeginForm("Create", "Player", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group" >
        @Html.LabelFor(model => model.Name, "Imię", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Surname, "Nazwisko", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Nationality, "Narodowość", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nationality, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nationality, "", new { @class = "text-danger" })
        </div>
    </div>





    <div class="form-group">
        @Html.LabelFor(model => model.Brithday, "Data urodzenia", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Brithday, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Brithday, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Position, "Pozycja", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.Position, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Examination, "Termin badań", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Examination, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Examination, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="editor-field">
        @Html.LabelFor(model => model.ImgSource,"Zdjęcie", htmlAttributes: new { @class = "control-label col-md-2" })
        <input id="ImagePath" title="Upload a product image"
               type="file" name="file" />
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Dodaj" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Wróć do listy", "List")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ClubManagement/Views/Player/Details.cshtml
@model ClubManagement.Models.Player

@{
    ViewBag.Title = "Details";
}

<h4 style="text-align:center; font-size:50px;">@Html.DisplayFor(model => model.Name) @Html.DisplayFor(model => model.Surname)</h4>
<hr />
<div style="text-align:center"><img src="~/Content/Images/@Html.DisplayFor(model => model.ImgSource)" height=150 width=150 /></div>
<div>


    <dl class="dl-horizontal">


        <dt>
            Narodowość
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nationality)
        </dd>

        <dt>
            Data urodzenia
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brithday)
        </dd>

        <dt>
            Pozycja
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position)
        </dd>



        <dt>
            Ważność badań
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Examination)
        </dd>

    </dl>
</div>
<div id="container">


    <div class="box" style="float:left">
        <h2>Mecze: @Html.DisplayTextFor(model => model.Games) </h2>
    </div>
    <div class="box" style="float:left">
        <h2>Minuty: @Html.DisplayFor(model => model.Minutes)</h2>
    </div>
    <div class="box" style="float:left">
        <h2>Bramki: @Html.DisplayFor(model => model.Goals)</h2>
    </div>
    <div class="box" style="float:left">
        <h2>Asysty: @Html.DisplayFor(model => model.Assists)</h2>
    </div>
    <div class="box"style="float:left">
        <h2>Kartki: <img src="~/Content/Images/zkartka.png" height=24 width=16 />@Html.DisplayFor(model => model.YellowCards)  <img src="~/Content/Images/ckartka.png" height=24 width=16 />@Html.DisplayFor(model => model.RedCards)</h2>
    </div>
    <div class="box" style="float:left">
        <h2>Nieobecności: @Html.DisplayFor(model => model.Absence)</h2>
    </div>


</div>
<button class="button" onclick="@("window.location.href='" + @Url.Action("PlayedMatches", "Match", new { id = Model.id }) + "'");"> Rozegrane mecze</button>

<style>
    #container {
        position: relative;
        margin-top: auto;
        height: 75px;
       display:flex;
      
    }
    .box {
        box-shadow: 0 1px 4px rgba(0, 0, 0, 0.3), 0 0 40px rgba(0, 0, 0, 0.1) inset;
        padding-left: 4px;
        padding-right: 4px;
        text-align: center;
        width: auto;
        height: auto;
        margin: 5px;
        flex-grow: 4;
    }
</style>

ClubManagement/Views/Player/List.cshtml
@model IEnumerable<ClubManagement.Models.Player>

@{
    ViewBag.Title = "List";
}

<body>

    <h1 style="font-family:fantasy; text-align:center; font-size:50px">LISTA ZAWODNIKÓW</h1>

    <style>
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        tr:nth-child(odd) {
            background-color: #ffffff;
        }
    </style>

    <button class="mybutton" onclick="@("window.location.href='" + @Url.Action("Create", "Player") + "'");"> Dodaj zawodnika</button>
    <table class="content-table">

        <tr style="background-color:#808080">
            <th>
                Zdj
            </th>
            <th>
                Imię
            </th>
            <th>
                @Html.ActionLink("Nazwisko", "List", new { sortOrder = 11 })
            </th>
            <th>
                Narodowość
            </th>

            <th>
                @Html.ActionLink("Data urodzenia", "List", new { sortOrder = 1 })
            </th>

            <th>
                @Html.ActionLink("Pozycja", "List", new { sortOrder = 2 })
            </th>
            <th>
                @Html.ActionLink("Badania", "List", new { sortOrder = 3 })
            </th>
            <th>
                @Html.ActionLink("G", "List", new { sortOrder = 4 })
            </th>
            <th>
                @Html.ActionLink("A", "List", new { sortOrder = 5 })
            </th>
            <th>
                @Html.ActionLink("M", "List", new { sortOrder = 6 })
            </th>
            <th>
                @Html.ActionLink("MIN", "List", new { sortOrder = 7 })
            </th>


            <th>
                @Html.ActionLink("ŻK", "List", new { sortOrder = 8 })
            </th>
            <th>
                @Html.ActionLink("CK", "List", new { sortOrder = 9 })
            </th>
            <th>
                @Html.ActionLink("NB", "List", new { sortOrder = 10 })
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @if (item.ReadyToPlay)

                    {<img src="~/Content/Images/ptaszek.png" alt="" height=25 width=25> }
                    else
                    {<img src="~/Content/Images/x.png" alt="" height=25 width=25>}
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Surname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nationality)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Brithday)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Position)
                </td>
                <td>
                    <font style="color:@item.examColor">   @Html.DisplayFor(modelItem => item.Examination)</font>


                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Goals)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Assists)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Games)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Minutes)
                </td>
                <td bgcolor="@item.yellowCardsColor">

                    @Html.DisplayFor(modelItem => item.YellowCards)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RedCards)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Absence)
                </td>

                <td>
                    <a href='@Url.Action("Details", "Player",new { id = item.id })'>
                        <img src="~/Content/Images/staty.png" alt="" height=20 width=20 title="Statystyki">
                    </a>
                    <a href='@Url.Action("EditInfo", "Player",new { id = item.id })'>
                        <img src="~/Content/Images/badania.png" alt="" height=20 width=20 title="Termin badań">
                    </a>
                    <a href='@Url.Action("Delete", "Player",new { id = item.id })'>
                        <img src="~/Content/Images/delete.png" alt="" height=20 width=20 title="Usuń">
                    </a>

                </td>
            </tr>
        }

    </table>
</body>
<style>
    a{
        color:white;
       
    }
        a:hover {
            color:black;
        }

    .content-table {
        border-collapse: collapse;
        margin: 25px 0;
        margin-left: auto;
        margin-right: auto;
        min-width: 600px;
        border-radius: 5px 5px 0 0;
        overflow: hidden;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
    }

        .content-table thead tr {
            background-color: #009879;
            color: #ffffff;
            text-align: left;
            font-weight: bold;
        }

        .content-table th {
            padding: 12px 15px;
          
        }
        .content-table td {
            padding: 12px 15px;
        }

        .content-table tbody tr {
            border-bottom: 1px solid #dddddd;
        }

            .content-table tbody tr:nth-of-type(even) {
                background-color: #f3f3f3;
            }

            .content-table tbody tr:last-of-type {
                border-bottom: 2px solid #808080;
            }

            .content-table tbody tr.active-row {
                font-weight: bold;
                color: #009879;
            }
    .multibutton {
        margin-left: auto;
        margin-right: auto;
        margin-top: auto;
        margin-bottom: auto;
    }

    .mybutton {
        text-decoration: none;
        text-align: center;
        color: #3cbabe;
        border: 2px solid #3cbabe;
        border-radius: 4px;
        position: relative;
        width: 150px;
        line-height: 40px;
        display: inline-block;
        font-family: Arial;
        font-weight: 600;
        overflow: hidden;
    }

        .mybutton:before {
            content: "";
            background-color: rgba(255,255,255,0.5);
            height: 100%;
            width: 40px;
            display: block;
            position: absolute;
            top: 0;
            left: -70px;
            transform: skewX(-45deg) translateX(0px);
            transition: none;
        }

        .mybutton:hover {
            background-color: #3cbabe;
            color: #ffffff;
            border-bottom: 2px solid #319598;
        }

            .mybutton:hover:before {
                transform: skewX(-45deg) translateX(250px);
                transition: all 0.4s ease-in;
            }
</style>