ClubManagement/Controllers/EventController.cs
using ClubManagement.DAL;
using ClubManagement.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using static ClubManagement.Models.Event;

namespace ClubManagement.Controllers
{
    public class EventController : Controller
    {
        // GET: Calendar
        List<DateTime> dateList = new List<DateTime>();
        List<DateTime> timeList = new List<DateTime>();
        [Authorize]
        public ActionResult List()
        {
            ClubContext db = new ClubContext();
            
            var events =
            from e in db.Events
            select e;

            events = events.OrderBy(s=>s.Day);
            return View(events.ToList());
        }
        public ActionResult CreateSoloTraining()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateSoloTraining(Event eventToView)
        {
            if (!ModelState.IsValid) return View("CreateSoloTraining", eventToView);
            else
            {
                
                Event e = new Event
                {

                    Day = eventToView.Day,
                    Time= eventToView.Time,
                    Id= eventToView.Id,
                    EventName=EventType.trening,
                    EventPlace=eventToView.EventPlace,
                    Opponent="-",
                    Info=eventToView.Info,


                };
                ClubContext db = new ClubContext();
                db.Events.Add(e);
                db.SaveChanges();
            }

            return RedirectToAction("List");
        }

        public ActionResult CreateMatch()
        {
            ClubContext db = new ClubContext();
            IEnumerable<Opponent> opponents = db.Opponents.ToList();
            ViewBag.Opponents = opponents;
            return View();
        }
        [HttpPost]
        public ActionResult CreateMatch(Event eventToView)
        {
          
            if (!ModelState.IsValid) return View("CreateMatch", eventToView);
            else
            {
                ClubContext db = new ClubContext();
                Opponent opponent = new Opponent();
                opponent = db.Opponents.Find(eventToView.OpponentID);
                Event e = new Event
                {
                    Day = eventToView.Day,
                    Time = eventToView.Time,
                    Id = eventToView.Id,
                    EventName = EventType.mecz,
                    EventPlace = Place.inne,
                    Opponent =opponent.Name,
                    OpponentIMG=opponent.ImgSource,
                    Info = eventToView.Info,
                    OpponentID=eventToView.OpponentID,
                    Away=eventToView.Away,

                };
                
                db.Events.Add(e);
                db.SaveChanges();
            }
            
            return RedirectToAction("List");
        }
        public ActionResult CreateMultiTraining()
        {
            
            return View();
        }
        [HttpPost]
        public ActionResult CreateMultiTraining(Event eventToView,FormCollection collection)
        {
            if (!ModelState.IsValid) return View("CreateMatch", eventToView);
            else if(Convert.ToInt64(collection["warun"])==0)
            {
                DateTime valueDa = Convert.ToDateTime(collection["Day"]);
                TimeSpan valueTi = Convert.ToDateTime(collection["Time"]).TimeOfDay;
                DateTime result = valueDa + valueTi;
                dateList.Add(result);
                return View("CreateMatch", eventToView);
            }
            else
            {

                DateTime valueDa = Convert.ToDateTime(collection["Day"]);
                TimeSpan valueTi = Convert.ToDateTime(collection["Time"]).TimeOfDay;
                DateTime result = valueDa + valueTi;
               
                foreach (DateTime data in dateList)
                {
                    Event e = new Event
                    {
                        EventPlace = eventToView.EventPlace,
                        Info = eventToView.Info,
                        Day = data.Date,
                        Time = data.Date,


                    };
                    ClubContext db = new ClubContext();
                    db.Events.Add(e);
                    db.SaveChanges();
                }
                dateList = null;
            }
            
            return RedirectToAction("List");
        }
        public void AddList(FormCollection collection)
        {
           
            
           
        }
        public ActionResult Delete(int id)
        {
            ClubContext db = new ClubContext();
            Event e = new Event();
            e = db.Events.Find(id);
            db.Events.Remove(e);
            db.SaveChanges();
           
            return RedirectToAction("List");
        }
        public ActionResult Edit(int id)
        {
            ClubContext db = new ClubContext();
            Event e= new Event();
            db.Events.Attach(e);
            e = db.Events.Find(id);
            Event eToView = new Event
            {
                Day = e.Day,
                Time = e.Time,
                EventPlace = e.EventPlace,
                Info = e.Info,
            };
            return View(eToView);
        }
        [HttpPost]
        public ActionResult Edit(Event eToView, int id)
        {
            ClubContext db = new ClubContext();
            Event e = new Event();
            db.Events.Attach(e);
            e = db.Events.Find(id);
            e.AwayPlace = eToView.AwayPlace;
            e.Day = eToView.Day;
            e.EventPlace = eToView.EventPlace;
            e.Info = eToView.Info;
            e.Time = eToView.Time;
            db.Entry(e).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("List");

        }
    }
    }

ClubManagement/Controllers/MatchController.cs
using ClubManagement.DAL;
using ClubManagement.Models;
using ClubManagement.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClubManagement.Controllers
{
    public class MatchController : Controller
    {
        // GET: Match
        [Authorize]
        public ActionResult List()
        {
            ClubContext db = new ClubContext();

            var matches =
            from e in db.Matches
            select e;

            matches = matches.OrderByDescending(s => s.Day);
            

            return View(matches.ToList());
        }
        public ActionResult Delete(int id)
        {
            ClubContext db = new ClubContext();
            Match match = new Match();
            db.Matches.Attach(match);
            match = db.Matches.Find(id);
            db.Matches.Remove(match);
            db.SaveChanges();
            return RedirectToAction("List");
        }
        public ActionResult AddPlayers(int id)
        {
            ClubContext db = new ClubContext();
            Match match = new Match();
            db.Matches.Attach(match);
            match = db.Matches.Find(id);
            ViewBag.Name = match.Opponent;
            ViewBag.Day = match.Day.Date;
            List<Player> playersList = db.Players.ToList();
            List<string> playersListString = new List<string>();

            Match m = new Match()
            {

                Players = playersList,

            };

            return View(m);
        }
        [HttpPost]
        public ActionResult AddPlayers(Training training, int id, FormCollection colletion)
        {
            var b = colletion["Players"].ToString();
           
            b.ToArray();
            ClubContext db = new ClubContext();
            Match match = new Match();
            List<Player> matchPlayers = new List<Player>();
            string[] splitted = b.Split(',');
            int[] ids = new int[splitted.Length];

            for (int i = 0; i < splitted.Length; i++)
            {
                ids[i] = int.Parse(splitted[i]);
            }
            for (int i=0; i<ids.Count(); i++)
            {
                matchPlayers.Add(db.Players.Find(ids[i]));
            }
            
            string lista = "";
            string name = "";
            Player player = new Player();
            foreach (var item in matchPlayers)
            {
                db.Players.Attach(item);
                player = db.Players.Find(Convert.ToInt32(item.id));
                player.Games++;
                db.Entry(player).State = EntityState.Modified;
                db.SaveChanges();
                name = player.Name + " " + player.Surname;
                lista = lista + name + ", ";
            }

            Match match1 = new Match();
            db.Matches.Attach(match1);
            match1 = db.Matches.Find(id);
            match1.IdPlayers =  string.Join(",",ids); 
            match1.Updated = true;
            match1.PlayersString = lista;
            db.Entry(match1).State = EntityState.Modified;
            db.SaveChanges();


            return RedirectToAction("List");
        }
        public ActionResult Details(int id)
        {
            ClubContext db = new ClubContext();

            Match m = new Match();
            db.Matches.Attach(m);
            m = db.Matches.Find(id);

            return View(m);
        }
        public ActionResult AddStats(int id)
        {
            ClubContext db = new ClubContext();
            Match m = new Match();
            db.Matches.Attach(m);
            m = db.Matches.Find(id);
            if (!m.Updated)
            {
                Response.Write("<script>alert('Data inserted successfully')</script>");
                return RedirectToAction("List");
            }
            else
            {
                List<Player> players = new List<Player>();
                List<PlayerToMatch> playersVM = new List<PlayerToMatch>();
                PlayerToMatch pVM;
                List<PlayerToMatch> checkMatch = db.PlayerToMatches.ToList();
                string[] splitted = m.IdPlayers.Split(',');
                int[] ids = new int[splitted.Length];

                for (int i = 0; i < splitted.Length; i++)
                {
                    ids[i] = int.Parse(splitted[i]);
                }

                for (int i = 0; i < ids.Count(); i++)
                {
                    players.Add(db.Players.Find(ids[i]));

                }
                ViewBag.MatchDay = m.Time;
                ViewBag.Opponent = m.Opponent;
                ViewBag.Score = m.GoalsLost.ToString() + ":" + m.GoalsScored.ToString();
                if (!m.AddedPLayersToMatch)
                {

                    foreach (Player item in players)
                    {

                        pVM = new PlayerToMatch
                        {
                            PlayerId = item.id,
                            MatchId = m.Id,
                            Name = item.Name,
                            Surname = item.Surname,
                            YellowCards = 0,
                            RedCards = 0,
                            Goals = 0,
                            Minutes = 0,
                            Rating = 0,
                            Assists = 0,

                        };
                        playersVM.Add(pVM);
                        db.PlayerToMatches.Add(pVM);
                        db.SaveChanges();

                    }

                }

                m.AddedPLayersToMatch = true;
                db.SaveChanges();
                List<PlayerToMatch> playersToView = db.PlayerToMatches.Where(item => item.MatchId == id).OrderByDescending(item => item.Minutes).ToList();
                return View(playersToView);
            }
        }

        public ActionResult Edit(int id)
        {
            ClubContext db = new ClubContext();
            PlayerToMatch p = db.PlayerToMatches.Find(id);
            Match m = db.Matches.Find(p.MatchId);

            ViewBag.Opponent = m.Opponent;
            return View(p);
        }
        [HttpPost]
        public ActionResult Edit(PlayerToMatch p,int id)
        {

            ClubContext db = new ClubContext();
            PlayerToMatch player = new PlayerToMatch();
            Player playerToAdd = new Player();
            
            db.PlayerToMatches.Attach(player);
            player = db.PlayerToMatches.Find(id);
            playerToAdd = db.Players.Find(player.PlayerId);
            playerToAdd.YellowCards = playerToAdd.YellowCards + p.YellowCards;
            playerToAdd.RedCards = playerToAdd.RedCards + p.RedCards;
            playerToAdd.Minutes = playerToAdd.Minutes + p.Minutes;
            playerToAdd.Assists = playerToAdd.Assists + p.Assists;
            playerToAdd.RatingSum = playerToAdd.RatingSum + p.Rating;
            db.PlayerToMatches.Attach(player);
            player = db.PlayerToMatches.Find(id);

            player.YellowCards = p.YellowCards;
            player.RedCards = p.RedCards;
            player.Minutes = p.Minutes;
            player.Goals = p.Goals;
            player.Assists = p.Assists;
            player.Rating = p.Rating;

            db.Entry(playerToAdd).State = EntityState.Modified;
            db.Entry(player).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("AddStats", new { id = player.MatchId });
        }

        public ActionResult EditMatch (int id)
        {
            ClubContext db = new ClubContext();
            Match m = db.Matches.Find(id);
            return View(m);
        }
        [HttpPost]
        public ActionResult EditMatch (Match m, int id)
        {
            ClubContext db = new ClubContext();
            Match match = db.Matches.Find(id);
            match.GoalsLost = m.GoalsLost;
            match.GoalsScored = m.GoalsScored;
            Opponent oponnent = db.Opponents.Find(match.OpponentID);
            if (m.GoalsScored > m.GoalsLost) oponnent.Wins++;
            else if (m.GoalsScored < m.GoalsLost) oponnent.Loses++;
            else oponnent.Draws++;
            oponnent.LostGoals = oponnent.LostGoals + m.GoalsLost;
            oponnent.ScoredGoals = oponnent.ScoredGoals + m.GoalsScored;
            db.Entry(match).State = EntityState.Modified;
            db.Entry(oponnent).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("List");
        }
        public ActionResult PlayedMatches ( int id)
        {
            ClubContext db = new ClubContext();
            List<PlayerToMatch> matches = db.PlayerToMatches.Where(s => s.PlayerId == id).ToList();
            return View(matches);

        }
      
    }
}

ClubManagement/Controllers/NewsController.cs
using ClubManagement.DAL;
using ClubManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClubManagement.Controllers
{
    public class NewsController : Controller
    {
        // GET: News
        [Authorize]
        public ActionResult List()
        {
            ClubContext db = new ClubContext();

            List<News> news = db.News.OrderByDescending(n=>n.Posted).ToList();
            
            return View(news);
        }
        
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(News news)
        {
            if (!ModelState.IsValid) return View("Create", news);
            else
            {
                News n = new News
                {
                    Id = news.Id,
                    Title = news.Title,
                    Author = news.Author,
                    Contents = news.Contents,
                    Posted = DateTime.Now,

                };
                ClubContext db = new ClubContext();
                db.News.Add(n);
                db.SaveChanges();
            }

            return RedirectToAction("List");
        }
        public ActionResult Delete (int id)
        {
            ClubContext db = new ClubContext();
            News news = new News();
            db.News.Attach(news);
            news = db.News.Find(id);
            db.News.Remove(news);
            db.SaveChanges();
            return RedirectToAction("List");
        }

    }
}

ClubManagement/Views/Home/MainPage.cshtml
<div class="tytul">
    <h1 style="font-family:fantasy;  font-size:50px">CZARNI CZARNA BIAŁOSTOCKA</h1>
    <p><a href="http://www.90minut.pl/liga/1/liga11274.html" class="btn btn-primary btn-lg">Tabela &raquo;</a></p>
    <div id="namecze">
        <div class="boxnextMatch">
            <h2 style="font-weight:bold">Najbliższy Mecz</h2>
            @if (ViewBag.IsMatch)
            {
                <p class="nextMatch1"> CZARNI CZARNA<img src="~/Content/Images/czarni.jpg" height=75 width=75></p>
                <p class="nextMatch2">VS</p>
                <p class="nextMatch3"> <img src="~/Content/Images/@ViewBag.Img" height=75 width=75>@ViewBag.MatchOpponent</p>
                <p>Data:  @ViewBag.MatchDay Miejsce: @ViewBag.MatchPlace</p>
                <p><a class="btn btn-default" href='@Url.Action("Details", "Opponent", new { id = ViewBag.NextMatchOpponentID })'>Sprawdź przeciwnika &raquo;</a></p>
            }
            else
            {
                <p class="nextMatch2">BRAK DANYCH O MECZU</p>
                <p><a class="btn btn-default" href='@Url.Action("CreateMatch", "Event", new { id = ViewBag.NextMatchOpponentID })'>Dodaj mecz &raquo;</a></p>
            }



        </div>
        <div class="boxnextMatch">
            <h2 style="font-weight:bold">Ostatni Mecz</h2>
            <p class="nextMatch1">CZARNI CZARNA<img src="~/Content/Images/czarni.jpg" height=75 width=75></p><p class="nextMatch2">@ViewBag.LastMatchScored : @ViewBag.LastMatchLost </p><p class="nextMatch3"> <img src="~/Content/Images/@ViewBag.LastMatchImg" height=75 width=75> @ViewBag.LastMatchOpponent</p>
            <p>Data:  @ViewBag.LastMatchDay</p>



            <p><a class="btn btn-default" href='@Url.Action("AddStats", "Match", new { id = ViewBag.LastMatchID })'>Zobacz statystyki &raquo;</a></p>
        </div>
    </div>
</div>

<div id="dolne">
    <div class="box">
        @if (ViewBag.IsTraining)
        {
        <h2 class="naglowek">Najbliższy Trening</h2>
        <p>Data:  @ViewBag.TrainingHour </p>
        <p>Miejsce: @ViewBag.TrainingPlace </p>
        <p><a class="btn btn-default" href='@Url.Action("List", "Event")'>Kalendarz &raquo;</a></p>
        }
        else
        {
        <h2 class="naglowek">Brak treningów</h2>
        <p><a class="btn btn-default" href='@Url.Action("CreateSoloTraining", "Event")'>Dodaj &raquo;</a></p>
        }
    </div>


    @*<div class="col-md-4">
            <h2>Zawodnicy</h2>
            <p>
                Aktualna ilość zawodników: @ViewBag.Size
            </p>
            <p><a class="btn btn-default" href='@Url.Action("List", "Player")'>Wszyscy &raquo;</a></p>
        </div>
    *@
    <div class="box">
        <h2 class="naglowek">Składki</h2>
        <p>Zaległe składki: @ViewBag.Unpaid</p>
        <p>Uzbierana Kwota: @ViewBag.Paid </p>
        <p><a class="btn btn-default" href='@Url.Action("List", "Penalty")'>Szczegóły &raquo;</a></p>
    </div>

    
        <div class="box">
            <h2 class="naglowek">Ostatnia wiadomość</h2>
            <b>@ViewBag.Title </b>
            <p>@ViewBag.Content</p>
            <p>@ViewBag.Posted</p>
            <p><a class="btn btn-default" href='@Url.Action("List", "News")'>Wszystkie &raquo;</a></p>
        </div>
  
</div>
<style>
    #namecze {
        display: flex;
    }
    .tytul {
        text-align: center;
        background-color: lightgrey;
        
        border-radius: 10px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
    }
    .boxnextMatch {
        border: 2px solid black;
        border-radius: 10px;
        margin: auto;
        margin-bottom: 5px;
        margin-top: 5px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
        max-width: 500px;
        background-color: ghostwhite;
    }
    .nextMatch1 {
        display: inline;
        font-weight: bold;
    }
    .nextMatch2 {
        display: inline;
        font-weight: bold;
    }
    .nextMatch3 {
        display: inline;
        font-weight: bold;
    }
    #dolne {
        justify-content:space-between;
            display:flex;

         
    }
    .box {
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
        border-radius: 10px;
        width: 300px;
        border: 2px solid black;
        padding: 10px;
        margin-top: 10px;
        background-color: ghostwhite;
        
    }
    .naglowek{
        text-align:center;
    }

    
</style>