ClubManagement/Models/Opponent.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ClubManagement.Models
{
    public class Opponent
    {
        [Key]
        public int Id { get; set;  }
        [Required(ErrorMessage = "Wymagane pole")]
        public string Name { get; set;  }
        [DataType(DataType.Upload)]
        [Display(Name = "Upload File")]
       
        public string ImgSource { get; set; }
        public int Wins { get; set; }
        public int Loses { get; set;  }
        public int Draws { get; set; }
        public int ScoredGoals { get; set; }
        public int LostGoals { get; set; }
    }
}

ClubManagement/Controllers/OpponentController.cs
using ClubManagement.DAL;
using ClubManagement.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClubManagement.Controllers
{
    public class OpponentController : Controller
    {
        // GET: Opponent
        [Authorize]
        public ActionResult Index()
        {
            ClubContext db = new ClubContext();
            List<Opponent> opponents = db.Opponents.ToList();
            return View(opponents);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Opponent opponentFromView, HttpPostedFileBase file)
        {

            string path;
       
            if (!ModelState.IsValid) return View("Create", opponentFromView);
            else
            {
                Opponent opponent = new Opponent
                {
                    Id = opponentFromView.Id,
                    Name = opponentFromView.Name,
                    LostGoals=0,
                    ScoredGoals=0,
                    Loses=0,
                    Wins=0,
                    Draws=0,
                };

                

                    

                   
                        path = Path.Combine(Server.MapPath("~/Content/Images"), Path.GetFileName(file.FileName));
                        file.SaveAs(path);
                        opponent.ImgSource = file.FileName;
                    
                    
             
              
                

                ClubContext db = new ClubContext();
                db.Opponents.Add(opponent);
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            ClubContext db = new ClubContext();
            Opponent op = new Opponent();
            db.Opponents.Attach(op);
            op = db.Opponents.Find(id);
            db.Opponents.Remove(op);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult CreateNew()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateNew(Opponent opponentFromView, HttpPostedFileBase file)
        {

            string path;

            if (!ModelState.IsValid) return View("Create", opponentFromView);
            else
            {
                Opponent opponent = new Opponent
                {
                    Id = opponentFromView.Id,
                    Name = opponentFromView.Name,
                    LostGoals = 0,
                    ScoredGoals = 0,
                    Loses = 0,
                    Wins = 0,
                    Draws = 0,
                };



               


                path = Path.Combine(Server.MapPath("~/Content/Images"), Path.GetFileName(file.FileName));
                file.SaveAs(path);
                opponent.ImgSource = file.FileName;






                ClubContext db = new ClubContext();
                db.Opponents.Add(opponent);
                db.SaveChanges();
            }

            return RedirectToAction("CreateMatch","Event");
        }
        public ActionResult Details (int id)
        {
            ClubContext db = new ClubContext();
            Opponent opponent = db.Opponents.Find(id);
            ViewBag.IMG = opponent.ImgSource;
            return View(opponent);
        }

    }
}

ClubManagement/Views/Opponent/Create.cshtml
@model ClubManagement.Models.Opponent

@using (Html.BeginForm("Create", "Opponent", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Dodaj nowego przeciwnika</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name,"Nazwa drużyny", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

   
    <div class="editor-field">
        @Html.LabelFor(model => model.ImgSource,"Wybierz zdjęcie", htmlAttributes: new { @class = "control-label col-md-2" })
        <input id="ImagePath" title="Upload a product image"
               type="file" name="file" />
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ClubManagement/Views/Opponent/CreateNew.cshtml
@model ClubManagement.Models.Opponent

@using (Html.BeginForm("CreateNew", "Opponent", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Opponent</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="editor-field">
            @Html.LabelFor(model => model.ImgSource, htmlAttributes: new { @class = "control-label col-md-2" })
            <input id="ImagePath" title="Upload a product image"
                   type="file" name="file" />
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ClubManagement/Views/Opponent/Delete.cshtml
@model ClubManagement.Models.Opponent

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Opponent</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImgSource)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImgSource)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Wins)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Wins)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Loses)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Loses)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Draws)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Draws)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ScoredGoals)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ScoredGoals)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LostGoals)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LostGoals)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ClubManagement/Views/Opponent/Details.cshtml
@model ClubManagement.Models.Opponent

<div>
    <h4 style="text-align:center; font-size:50px;">@Html.DisplayFor(model => model.Name)</h4>
    <hr />
    <div style="text-align:center"><img src="~/Content/Images/@Html.DisplayFor(model => model.ImgSource)" height=150 width=150 /></div>
    
        <div id="container">
        
            
        <div class="wygrane" style="float:left">
            <h2>Wygrane: @Html.DisplayTextFor(model =>model.Wins) </h2>
        </div>
        <div class="remisy"  style="float:left">
            <h2>Remisy: @Html.DisplayFor(model => model.Draws)</h2>
        </div>
        <div class="przegrane"  style="float:left">
            <h2>Przegrane: @Html.DisplayFor(model => model.Loses)</h2>
        </div>
        <div class="bilans"  style="float:left">
            <h2>Bilans bramek: @Html.DisplayFor(model => model.ScoredGoals) : @Html.DisplayFor(model => model.LostGoals) </h2>
        </div>
        
        </div>

  </div>  
<style>
    #container {
     
        position: relative;
        margin-top:auto;
      
        height:75px;
    }
    .wygrane {
        position: absolute;
        top: 0;
        left: 0;
        
        box-shadow: 0 1px 4px rgba(0, 0, 0, 0.3), 0 0 40px rgba(0, 0, 0, 0.1) inset;
    }
    .remisy {
        position: absolute;
        top: 0;
        left: 290px;
     
        box-shadow: 0 1px 4px rgba(0, 0, 0, 0.3), 0 0 40px rgba(0, 0, 0, 0.1) inset;
    }
    .przegrane {
        position: absolute;
        top: 0;
        left: 580px;
       
        box-shadow: 0 1px 4px rgba(0, 0, 0, 0.3), 0 0 40px rgba(0, 0, 0, 0.1) inset;
    }
    .bilans {
        position: absolute;
        top: 0;
        left: 870px;
        
        box-shadow: 0 1px 4px rgba(0, 0, 0, 0.3), 0 0 40px rgba(0, 0, 0, 0.1) inset;
    }
</style>

ClubManagement/Views/Opponent/Index.cshtml
@model IEnumerable<ClubManagement.Models.Opponent>


<h1 style="font-family:fantasy; text-align:center; font-size:50px">PRZECIWNICY</h1>
<button class="mybutton" onclick="@("window.location.href='" + @Url.Action("Create", "Opponent") + "'");"> Dodaj przeciwnika</button>
<div class="container">

    @foreach (var item in Model)
    {
        <div class="box">
            <div style="float:left">
                <img src="~/Content/Images/@item.ImgSource" width=150 height=150 />
            </div>
            <div style=" margin-left:20px; padding-left:10px;">
                <h2 style="text-align:center; text-decoration:underline;">@item.Name</h2>
                <p>Wygrane: @item.Wins</p>
                <p>Remisy: @item.Draws</p>
                <p>
                    Przegrane: @item.Loses


                    <a style="float:right" href='@Url.Action("Delete", "Opponent",new { id = item.Id })'>
                        <img src="~/Content/Images/delete.png" alt="" height=20 width=20 title="Usuń">
                    </a>
                    <a style="float:right" href='@Url.Action("Details", "Opponent",new { id = item.Id })'>
                        <img src="~/Content/Images/staty.png" alt="" height=20 width=20 title="Usuń">
                    </a>
                </p>
            </div>
        </div>

    }
</div>
<style>
    .box {
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
        border-radius: 10px;
        width: 500px;
        height: auto;
        border: 2px solid black;
        padding-left: 10px;
        padding-right: 10px;
        margin-top: 10px;
        background-color: ghostwhite;
        float: left;
        margin-left: 10px;
        margin-left: 10px;
        background-color: dodgerblue;
        color: white;
    }

    .naglowek {
        text-align: center;
        text-decoration: underline;
    }

    .containter {
        flex-wrap:nowrap;
        flex-direction:column;
        justify-content:space-around;
    }

    .mybutton {
        text-decoration: none;
        text-align: center;
        color: #3cbabe;
        border: 2px solid #3cbabe;
        border-radius: 4px;
        position: relative;
        width: 150px;
        line-height: 40px;
        display: inline-block;
        font-family: Arial;
        font-weight: 600;
        overflow: hidden;
    }

        .mybutton:before {
            content: "";
            background-color: rgba(255,255,255,0.5);
            height: 100%;
            width: 40px;
            display: block;
            position: absolute;
            top: 0;
            left: -70px;
            transform: skewX(-45deg) translateX(0px);
            transition: none;
        }

        .mybutton:hover {
            background-color: #3cbabe;
            color: #ffffff;
            border-bottom: 2px solid #319598;
        }

            .mybutton:hover:before {
                transform: skewX(-45deg) translateX(250px);
                transition: all 0.4s ease-in;
            }
</style>