ClubManagement/Models/Penalty.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ClubManagement.Models
{
    public class Penalty
    {
        [Key]
        public int Id{get; set;}

        public PenaltyType Type { get; set; }
        
        public string Player { get; set; }
        public bool Status { get; set; }
        public string Description { get; set; }

        public string Color
        {
            get
            {
                if (!Status) return "red";
                else return "green";
            }
        }
        public string StatusText
        {
            get
            {
                if (!Status) return "nieopłacono";
                else return "opłacono";
            }
        }
         public int Value
        {

            get;


            set;
        }

        public enum PenaltyType
        {
            spóźnienie,
            nieobecność,
            nieprzygotowanie,
            inne,
        };
    }
}

ClubManagement/Controllers/PenaltyController.cs
using ClubManagement.DAL;
using ClubManagement.Models;
using ClubManagement.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClubManagement.Controllers
{
    public class PenaltyController : Controller
    {
        // GET: Penalty
        [Authorize]
        public ActionResult List(int? value)
        {
            ClubContext mDb = new ClubContext();
            int paid=0, unpaid=0;
            List<Penalty> penaltiesList = mDb.Penalties.ToList();
            var penaltiesPaid = penaltiesList.Where(x => x.Status == true);
            var penaltiesUnpaid= penaltiesList.Where(x => x.Status == false);
            //sss
            foreach (var item in penaltiesList)
            {
                if (item.Status) paid = paid + item.Value;
                else unpaid = unpaid + item.Value;
            }
            ViewBag.Unpaid = unpaid;
            ViewBag.Paid = paid;
            if(value==0) return View(penaltiesPaid);
            else if(value==1) return View(penaltiesUnpaid);
            return View(penaltiesList);

        }
        
        public ActionResult Create()
        {
            ClubContext mDb = new ClubContext();
            List<Player> playersList = mDb.Players.ToList();
            var viewModel = new CreatePenaltyVM()
            {
                Players = playersList,
        };

            return View(viewModel);
        }
        [HttpPost]
        public ActionResult Create(Penalty penalty)

        {
            if (!ModelState.IsValid) return View("Create", penalty);
            
            else
            {
                ClubContext db = new ClubContext();
                Player player = new Player();
                string name;
                db.Players.Attach(player);
                player = db.Players.Find(Convert.ToInt32(penalty.Player));
                name = player.Name + " " + player.Surname;
                Penalty p = new Penalty
                {
                    Id = penalty.Id,
                    Type = penalty.Type,
                    Status = false,
                    Player = name,
                    Description = penalty.Description,
                    Value=penalty.Value,
                    

                };

               
                db.Penalties.Add(p);
                db.SaveChanges();

                return RedirectToAction("List");
            }
        }
        public ActionResult Delete(int id)
        {
            ClubContext db = new ClubContext();
            Penalty penalty = new Penalty();
            db.Penalties.Attach(penalty);
            penalty = db.Penalties.Find(id);
            db.Penalties.Remove(penalty);
            db.SaveChanges();
            return RedirectToAction("List");
        }
        
        public ActionResult Set ( int id)
        {
            ClubContext db = new ClubContext();
            Penalty penalty = new Penalty();
            db.Penalties.Attach(penalty);
            penalty = db.Penalties.Find(id);
            if(penalty.Status==true)
            penalty.Status = false;
            else penalty.Status = true;
            db.SaveChanges();
            return RedirectToAction("List");
        }
    }
}

ClubManagement/Views/Penalty/Create.cshtml
@model ClubManagement.ViewModels.CreatePenaltyVM


<h1 style="font-family:fantasy; text-align:center; font-size:50px">DODAJ NOWĄ KARĘ</h1>



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(m => m.Player, "Zawodnik", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.Player, new SelectList(Model.Players, "Id", "Name"), new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Player, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type,"Rodzaj kary", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Type, "Rodzaj", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Description,"Opis", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(x => x.Description, "Opis", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(m => m.Value,"Wartość", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(x => x.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.Value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ClubManagement/Views/Penalty/List.cshtml
@model IEnumerable<ClubManagement.Models.Penalty>


<h1 style="font-family:fantasy; text-align:center; font-size:50px">LISTA KAR</h1>


<div class="multibutton">
    <button class="mybutton" onclick="@("window.location.href='" + @Url.Action("Create", "Penalty") + "'");"> Dodaj nową kare</button>
    <button class="mybutton" onclick="@("window.location.href='" + @Url.Action("List", "Penalty", new { value = 0 }) + "'");"> Pokaż zapłacone</button>
    <button class="mybutton" onclick="@("window.location.href='" + @Url.Action("List", "Penalty", new { value = 1}) + "'");"> Pokaż niezapłacone</button>
</div>
<style>
    tr:nth-child(even) {
        background-color: #f2f2f2;
    }

    tr:nth-child(odd) {
        background-color: #ffffff;
    }
</style>
<p style="text-align:center">
    Zapłacono: @ViewBag.Paid  Niezapłacono:  @ViewBag.Unpaid
</p>

<table class="content-table">
    <tr style="background-color:#808080">
        <th>
            Zawodnik
        </th>
        <th>
            Rodzaj
        </th>
        <th>
            Status
        </th>
        <th>
            Opis
        </th>
        <th>
            Wartość
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Player)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                <font color="@item.Color">
                    @Html.DisplayFor(modelItem => item.StatusText)
                </font>


            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Value)
            </td>
            <td>

                @Html.ActionLink("Ustaw", "Set", new { id = item.Id }) |

                @Html.ActionLink("Usuń", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

<style>
    .content-table {
        border-collapse: collapse;
        margin: 25px 0;
        margin-left: auto;
        margin-right: auto;
        min-width: 600px;
        border-radius: 5px 5px 0 0;
        overflow: hidden;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
    }

        .content-table thead tr {
            background-color: #009879;
            color: #ffffff;
            text-align: left;
            font-weight: bold;
        }

        .content-table th {
            padding: 12px 15px;
        }

        .content-table td {
            padding: 12px 15px;
        }

        .content-table tbody tr {
            border-bottom: 1px solid #dddddd;
        }

            .content-table tbody tr:nth-of-type(even) {
                background-color: #f3f3f3;
            }

            .content-table tbody tr:last-of-type {
                border-bottom: 2px solid #808080;
            }

            .content-table tbody tr.active-row {
                font-weight: bold;
                color: #009879;
            }

    .mybutton {
        text-decoration: none;
        text-align: center;
        color: #3cbabe;
        border: 2px solid #3cbabe;
        border-radius: 4px;
        position: relative;
        width: 150px;
        line-height: 40px;
        display: inline-block;
        font-family: Arial;
        font-weight: 600;
        overflow: hidden;
    }

        .mybutton:before {
            content: "";
            background-color: rgba(255,255,255,0.5);
            height: 100%;
            width: 40px;
            display: block;
            position: absolute;
            top: 0;
            left: -70px;
            transform: skewX(-45deg) translateX(0px);
            transition: none;
        }

        .mybutton:hover {
            background-color: #3cbabe;
            color: #ffffff;
            border-bottom: 2px solid #319598;
        }

            .mybutton:hover:before {
                transform: skewX(-45deg) translateX(250px);
                transition: all 0.4s ease-in;
            }

    .multibutton {
        padding-top: 15px;
        padding-bottom: 15px;
        margin: 0;
        top: 50%;
        left: 50%;
        margin: auto;
        text-align: center;
    }
</style>